{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.env }}
  namespace: {{ .Values.app.name }}-{{ .Values.app.env }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.env }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role_arn }}
{{- end }}
