---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.env }}
  namespace: {{ .Values.app.name }}-{{ .Values.app.env }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.env }}
  {{- if .Values.service.annotations }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
  selector:
    app: {{ .Values.app.name }}-{{ .Values.app.env }}
