name: Prepare Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
#       - name: Release Please
#         uses: googleapis/release-please-action@v4
#         with:
#           token: ${{ secrets.PAT }}
#           release-type: helm
